name: Update Languages
on:
  schedule:
    - cron: '11 19 * * MON'
  push:
    paths-ignore:
      - 'src/languages.json'
      - 'README.md'
jobs:
  update_colours:
    name: Update Languages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        
      - name: Install dependencies
        run: pdm install
      
      - name: Update languages
        run: pdm run github-languages.py

      - name: Commit
        run: |
          git config --local user.name "kjxbyz"
          git config --local user.email "kjxbyz888@outlook.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Update languages.json'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
